### ISSUE TITLE
test: use the go version from go.mod

### ISSUE THREAD

**Issue by DavidProdinger** [corazawaf/coraza-spoa#146]
According to the documentation of the github action [actions/setup-go](https://github.com/actions/setup-go?tab=readme-ov-file#getting-go-version-from-the-gomod-file) you can get the go version from the go.mod file.

Woludn't it be helpful to use this version instead of the hardcoded version in each test? (see below)
```yaml
- name: Set up Go
  uses: actions/setup-go@v5
  with:
    go-version: '1.22'
```

The better one, and always matching the go.mod file version would be:
```yaml
- name: Set up Go
  uses: actions/setup-go@v5
  with:
    go-version-file: 'go.mod'
```
