### ISSUE TITLE
spop: panic serving: Error handling request

### ISSUE THREAD

**Issue by security-database** [corazawaf/coraza-spoa#169]
Playing with the actual version, got an issue

i'm accessing http://[myurl]/default.aspx/.env

And got this panic:

```
{"level":"error","time":"2025-01-26T11:43:25+01:00","message":"[client \"127.0.0.1\"] Coraza: Warning. Restricted File Access Attempt [file \"rules/REQUEST-930-APPLICATION-ATTACK-LFI.conf\"] [line \"4533\"] [id \"930130\"] [rev \"\"] [msg \"Restricted File Access Attempt\"] [data \"Matched Data: .env found within REQUEST_FILENAME: /default.aspx/.env\"] [severity \"critical\"] [ver \"OWASP_CRS/4.9.0-dev\"] [maturity \"0\"] [accuracy \"0\"] [tag \"application-multi\"] [tag \"language-multi\"] [tag \"platform-multi\"] [tag \"attack-lfi\"] [tag \"paranoia-level/1\"] [tag \"OWASP_CRS\"] [tag \"capec/1000/255/153/126\"] [tag \"PCI/6.5.4\"] [hostname \"127.0.0.1\"] [uri \"/default.aspx/.env\"] [unique_id \"64dd1cd9-e674-4d9e-88e7-4bcfd8ab9ef2\"]"}
{"level":"error","time":"2025-01-26T11:43:25+01:00","message":"[client \"127.0.0.1\"] Coraza: Access denied (phase 2). Inbound Anomaly Score Exceeded (Total Score: 5) [file \"rules/REQUEST-949-BLOCKING-EVALUATION.conf\"] [line \"11674\"] [id \"949110\"] [rev \"\"] [msg \"Inbound Anomaly Score Exceeded (Total Score: 5)\"] [data \"\"] [severity \"emergency\"] [ver \"OWASP_CRS/4.9.0-dev\"] [maturity \"0\"] [accuracy \"0\"] [tag \"anomaly-evaluation\"] [tag \"OWASP_CRS\"] [hostname \"127.0.0.1\"] [uri \"/default.aspx/.env\"] [unique_id \"64dd1cd9-e674-4d9e-88e7-4bcfd8ab9ef2\"]"}
11:43AM DBG sending interruption error="interrupted with status 403 and action deny"
11:43AM PNC Error handling request error="transaction not found: 64dd1cd9-e674-4d9e-88e7-4bcfd8ab9ef2"
2025/01/26 11:43:25 spop: panic serving: Error handling request
goroutine 7 [running]:
github.com/dropmorepackets/haproxy-go/spop.(*protocolClient).runHandler.func1()
	/root/go/pkg/mod/github.com/dropmorepackets/haproxy-go@v0.0.5/spop/protocol.go:146 +0x70
panic({0x8ab800?, 0xc00128e8e0?})
	/snap/go/10818/src/runtime/panic.go:785 +0x132
github.com/corazawaf/coraza-spoa/internal.(*Agent).HandleSPOE.(*Logger).Panic.func4({0x9a56e9?, 0x0?})
	/root/go/pkg/mod/github.com/rs/zerolog@v1.33.0/log.go:405 +0x27
github.com/rs/zerolog.(*Event).msg(0xc000eb00e0, {0x9a56e9, 0x16})
	/root/go/pkg/mod/github.com/rs/zerolog@v1.33.0/event.go:158 +0x2aa
github.com/rs/zerolog.(*Event).Msg(...)
	/root/go/pkg/mod/github.com/rs/zerolog@v1.33.0/event.go:110
github.com/corazawaf/coraza-spoa/internal.(*Agent).HandleSPOE(0xc0007c94a0, {0xaf5c10, 0xc000576280}, 0xc000be2120, 0xc0014969f0)
	/root/coraza-spoa/internal/agent.go:95 +0x489
github.com/dropmorepackets/haproxy-go/spop.(*protocolClient).runHandler(0x4368a8?, {0xaf5c10?, 0xc000576280?}, 0x80?, 0xc001ff1d70?, 0xc000065d48?)
	/root/go/pkg/mod/github.com/dropmorepackets/haproxy-go@v0.0.5/spop/protocol.go:151 +0x77
github.com/dropmorepackets/haproxy-go/spop.(*protocolClient).onNotify.func1(0xc000be2120)
	/root/go/pkg/mod/github.com/dropmorepackets/haproxy-go@v0.0.5/spop/protocol.go:165 +0x8b
github.com/dropmorepackets/haproxy-go/spop.(*AckFrame).WriteTo(0xc000065e78, {0x7fd41035ce10, 0xc00011e708})
	/root/go/pkg/mod/github.com/dropmorepackets/haproxy-go@v0.0.5/spop/frames.go:144 +0x23d
github.com/dropmorepackets/haproxy-go/spop.(*protocolClient).onNotify(0xc0000811a0, 0xc000422380)
	/root/go/pkg/mod/github.com/dropmorepackets/haproxy-go@v0.0.5/spop/protocol.go:182 +0x205
github.com/dropmorepackets/haproxy-go/spop.(*protocolClient).frameHandler(0xc000100180?, 0xc001d55d58?)
	/root/go/pkg/mod/github.com/dropmorepackets/haproxy-go@v0.0.5/spop/protocol.go:61 +0x65
github.com/dropmorepackets/haproxy-go/spop.(*asyncScheduler).queueWorker(0xc0000520c8)
	/root/go/pkg/mod/github.com/dropmorepackets/haproxy-go@v0.0.5/spop/scheduler.go:94 +0x37
created by github.com/dropmorepackets/haproxy-go/spop.newAsyncScheduler in goroutine 23
	/root/go/pkg/mod/github.com/dropmorepackets/haproxy-go@v0.0.5/spop/scheduler.go:85 +0x148

{"level":"error","time":"2025-01-26T11:43:26+01:00","message":"[client \"127.0.0.1\"] Coraza: Warning. OS File Access Attempt [file \"rules/REQUEST-930-APPLICATION-ATTACK-LFI.conf\"] [line \"4506\"] [id \"930120\"] [rev \"\"] [msg \"OS File Access Attempt\"] [data \"Matched Data: .env found within ARGS:ReturnUrl: /default.aspx/.env\"] [severity \"critical\"] [ver \"OWASP_CRS/4.9.0-dev\"] [maturity \"0\"] [accuracy \"0\"] [tag \"application-multi\"] [tag \"language-multi\"] [tag \"platform-multi\"] [tag \"attack-lfi\"] [tag \"paranoia-level/1\"] [tag \"OWASP_CRS\"] [tag \"capec/1000/255/153/126\"] [tag \"PCI/6.5.4\"] [hostname \"127.0.0.1\"] [uri \"/Login.aspx?ReturnUrl=%2fdefault.aspx%2f.env\"] [unique_id \"7fcb21a0-783f-4a01-9de2-f91e16c1a390\"]"}
{"level":"error","time":"2025-01-26T11:43:26+01:00","message":"[client \"127.0.0.1\"] Coraza: Access denied (phase 2). Inbound Anomaly Score Exceeded (Total Score: 5) [file \"rules/REQUEST-949-BLOCKING-EVALUATION.conf\"] [line \"11674\"] [id \"949110\"] [rev \"\"] [msg \"Inbound Anomaly Score Exceeded (Total Score: 5)\"] [data \"\"] [severity \"emergency\"] [ver \"OWASP_CRS/4.9.0-dev\"] [maturity \"0\"] [accuracy \"0\"] [tag \"anomaly-evaluation\"] [tag \"OWASP_CRS\"] [hostname \"127.0.0.1\"] [uri \"/Login.aspx?ReturnUrl=%2fdefault.aspx%2f.env\"] [unique_id \"7fcb21a0-783f-4a01-9de2-f91e16c1a390\"]"}
```

Hope the logs helps

**Comment by fionera** [comment]
You probably have response checking enabled inside coraza-spoa but not in the haproxy config. Thats why it can't find the transaction

**Comment by security-database** [comment]
Not sure, yes for the coraza.yaml conf, but in haproxy conf

coraza.yml :

```
# The SPOA server bind address
bind: 0.0.0.0:9000

# Process request and response with this application if provided app name is not found.
# You can remove or comment out this config param if you don't need "default_application" functionality.
log_level: debug
log_file: /dev/stdout
log_format: console

applications:
  - name: waf
    directives: |
      Include coraza.conf
      Include crs-setup.conf
      Include plugins/*-config.conf
      Include plugins/*-before.conf
      Include rules/*.conf
      Include plugins/*-after.conf

    # HAProxy configured to send requests only, that means no cache required
    response_check: true

    # The transaction cache lifetime in milliseconds (60000ms = 60s)
    transaction_ttl_ms: 60000
    # The maximum number of transactions which can be cached
    #transaction_active_limit: 100000

    # The log level configuration, one of: debug/info/warn/error/panic/fatal
    log_level: debug
    # The log file path
    log_file: /dev/stdout
    log_format: json
```

my haproxy setting (coraza.cfg) load by haproxy

```
[coraza]
spoe-agent coraza-agent
    messages   coraza-req     coraza-res
    option      var-prefix      coraza
    option      set-on-error    error
    timeout     hello           2s
    timeout     idle            2m
    timeout     processing      500ms
    use-backend coraza-spoa
    log         global


spoe-message coraza-req
    args app=str(waf) id=unique-id src-ip=src src-port=src_port dst-ip=dst dst-port=dst_port method=method path=path query=query version=req.ver headers=req.hdrs body=req.body
    event on-frontend-http-request

spoe-message coraza-res
    args app=str(waf) id=unique-id version=res.ver status=status headers=res.hdrs body=res.body
    event on-http-response
```
Do i miss something ?
